apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-persistent-storage
  namespace: jenkins
  labels:
    app: jenkins
#Kubernetes NFS-Client Provisioner Deployed - Automatated PVC Assigned    
  annotations:
    volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 6Gi
