apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-persistent-storage
  labels:
    app: jenkins
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 6Gi
